#!/usr/bin/env python3

from argparse import ArgumentParser, FileType
from os.path import basename
from requests import post
from subprocess import check_output

parser = ArgumentParser(description=
    'Upload files to https://gist.github.com/ and print the uploaded url to stdout.'
)
parser.add_argument(
    '-c',
    '--commit',
    metavar='COMMIT',
    type=str,
    default='HEAD',
    help='the commit to compare on'
)
parser.add_argument(
    '-s',
    '--secret',
    action='store_true',
    help='create secret gist'
)
parser.add_argument(
    '-d',
    '--description',
    metavar='DESC',
    type=str,
    default='uploaded from the command line like a pro with https://github.com/callum-oakley/gup',
    help='description for your gist'
)
parser.add_argument(
    '-t',
    '--token',
    metavar='TOKEN',
    type=str,
    required=True,
    help='github personal access token'
)
args = parser.parse_args()

contents = {}
file_names = check_output(['git', 'diff', '--name-only', args.commit])

for name in file_names.splitlines():
    file_content = check_output(['git', 'diff', args.commit, '--', name])
    contents[basename(name.decode("utf-8") + ".patch")] = {'content': file_content}

r = post(
    'https://api.github.com/gists',
    headers={'authorization': 'token {}'.format(args.token)},
    json={
      "description": args.description,
      "public": not args.secret,
      "files": contents
    }
)

if not r.ok:
    print('{}: error uploading gist: {}'.format(parser.prog, r.reason))
    exit(1)
print(r.json()['html_url'])

# TODO pip install, upload multiple files
